### ISSUE TITLE
I have error

### ISSUE THREAD

**Issue by liwsakilive** [SoInteractive/ansible-elasticsearch#19]
fatal: [graylog-staging]: FAILED! => {"changed": false, "failed": true, "msg": "Maximum memory for elasticsearch should not be greater than half of physycal RAM"}

**Comment by paulfantom** [comment]
You can set elasticsearch memory with `elasticsearch_memory` variable.

**Comment by jkrol2** [comment]
This error comes from preflight check: https://github.com/SoInteractive/ansible-elasticsearch/blob/master/tasks/preflight.yml

Elasticsearch documentation recommends no more than half of physical RAM for heap size: https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html

As @paulfantom previously wrote you can set elasticsearch heap size with `elasticsearch_memory` having in mind that limitation.
